customer:
  params:
    p1: 555
    p7: 0

spring:
  datasource:
    url: jdbc:h2:mem:customers-db
  data:
    rest:
      base-path: /api
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8081
